### ISSUE TITLE
Enorme Dúvida!

### ISSUE THREAD

**Issue by KAYOKG** [NickError404/CrudFullStack-Car-Shop#2]
Como criar um software eficiente e que atenda às necessidades dos usuários, ao mesmo tempo em que é escalável, fácil de manter e atualizar, e está em conformidade com as melhores práticas de desenvolvimento?

**Comment by SolarisSy** [comment]
Melhor prática de desenvolvimento conhecida por mim até hoje é a boa conciliação entre conhecimentos que já temos no mercado mas também sempre de olho na inovação, o fator essencial nesse equilíbrio é justamente pelo fato que a base é desempenho/estabilidade entre inovação
